version: "3.8"
services:
  react:
    image: emigr_app:1.0
    ports:
      - 3001:3000
  json_server:
    image: clue/json-server
    ports:
        - 3000:80
    volumes: 
        - /Users/arkhipchuk/Documents/emigr_ts/emigr_ts/src/store/db.json:/data/db.json
