version: "3.8"
services:
  react:
    build: .
    ports:
      - 3001:3000
    volumes: 
      - .:/app
  json_server:
    image: clue/json-server
    ports:
        - 3000:80
    volumes: 
        - ./src/store/db.json:/data/db.json
